name: Backend CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd apps/backend
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          cd apps/backend
          pytest

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd apps/backend
          pip install -r requirements.txt
          pip install flake8 black
      
      - name: Lint with flake8
        run: |
          cd apps/backend
          flake8 .
      
      - name: Format with black
        run: |
          cd apps/backend
          black .

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd apps/backend
          pip install -r requirements.txt
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd apps/backend
          # Build and push Docker image
          docker build -t vyuh-backend:$GITHUB_SHA .
          docker tag vyuh-backend:$GITHUB_SHA vyuh-backend:latest
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push vyuh-backend:latest
          
          # Deploy to AWS
          aws ecs update-service --cluster vyuh-cluster --service vyuh-service --force-new-deployment
